# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  # password: P@ssw0rd
  host: localhost
  port: 3306
  #database: rupeevest_nav
  #username: root
  #password: P@ssw0rd

  # socket: /tmp/mysql.sock
  socket: /tmp/mysqld.sock

development:
  <<: *default
  database: inventory

 
test:
  <<: *default
  database: inventory


production:
  <<: *default
  database: inventory
